apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mysql-data
  namespace: plataforma-academica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-auth
  namespace: plataforma-academica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-auth
  template:
    metadata:
      labels:
        app: db-auth
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: plataforma-config
                  key: AUTH_DB_NAME
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plataforma-secrets
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: auth-mysql-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: auth-mysql-data
          persistentVolumeClaim:
            claimName: auth-mysql-data
---
apiVersion: v1
kind: Service
metadata:
  name: db-auth
  namespace: plataforma-academica
spec:
  selector:
    app: db-auth
  ports:
    - port: 3306
      targetPort: 3306
