/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTurmasRouteImport } from './routes/_app.turmas'
import { Route as AppDisciplinasRouteImport } from './routes/_app.disciplinas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAtividadesRouteImport } from './routes/_app.atividades'
import { Route as AppTurmasIdRouteImport } from './routes/_app.turmas.$id'
import { Route as AppAtividadesIdRouteImport } from './routes/_app.atividades.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTurmasRoute = AppTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplinasRoute = AppDisciplinasRouteImport.update({
  id: '/disciplinas',
  path: '/disciplinas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAtividadesRoute = AppAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AppRoute,
} as any)
const AppTurmasIdRoute = AppTurmasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTurmasRoute,
} as any)
const AppAtividadesIdRoute = AppAtividadesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAtividadesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atividades': typeof AppAtividadesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/disciplinas': typeof AppDisciplinasRoute
  '/turmas': typeof AppTurmasRouteWithChildren
  '/atividades/$id': typeof AppAtividadesIdRoute
  '/turmas/$id': typeof AppTurmasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atividades': typeof AppAtividadesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/disciplinas': typeof AppDisciplinasRoute
  '/turmas': typeof AppTurmasRouteWithChildren
  '/atividades/$id': typeof AppAtividadesIdRoute
  '/turmas/$id': typeof AppTurmasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/atividades': typeof AppAtividadesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/disciplinas': typeof AppDisciplinasRoute
  '/_app/turmas': typeof AppTurmasRouteWithChildren
  '/_app/atividades/$id': typeof AppAtividadesIdRoute
  '/_app/turmas/$id': typeof AppTurmasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/atividades'
    | '/dashboard'
    | '/disciplinas'
    | '/turmas'
    | '/atividades/$id'
    | '/turmas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/atividades'
    | '/dashboard'
    | '/disciplinas'
    | '/turmas'
    | '/atividades/$id'
    | '/turmas/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/atividades'
    | '/_app/dashboard'
    | '/_app/disciplinas'
    | '/_app/turmas'
    | '/_app/atividades/$id'
    | '/_app/turmas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/turmas': {
      id: '/_app/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof AppTurmasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disciplinas': {
      id: '/_app/disciplinas'
      path: '/disciplinas'
      fullPath: '/disciplinas'
      preLoaderRoute: typeof AppDisciplinasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atividades': {
      id: '/_app/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AppAtividadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/turmas/$id': {
      id: '/_app/turmas/$id'
      path: '/$id'
      fullPath: '/turmas/$id'
      preLoaderRoute: typeof AppTurmasIdRouteImport
      parentRoute: typeof AppTurmasRoute
    }
    '/_app/atividades/$id': {
      id: '/_app/atividades/$id'
      path: '/$id'
      fullPath: '/atividades/$id'
      preLoaderRoute: typeof AppAtividadesIdRouteImport
      parentRoute: typeof AppAtividadesRoute
    }
  }
}

interface AppAtividadesRouteChildren {
  AppAtividadesIdRoute: typeof AppAtividadesIdRoute
}

const AppAtividadesRouteChildren: AppAtividadesRouteChildren = {
  AppAtividadesIdRoute: AppAtividadesIdRoute,
}

const AppAtividadesRouteWithChildren = AppAtividadesRoute._addFileChildren(
  AppAtividadesRouteChildren,
)

interface AppTurmasRouteChildren {
  AppTurmasIdRoute: typeof AppTurmasIdRoute
}

const AppTurmasRouteChildren: AppTurmasRouteChildren = {
  AppTurmasIdRoute: AppTurmasIdRoute,
}

const AppTurmasRouteWithChildren = AppTurmasRoute._addFileChildren(
  AppTurmasRouteChildren,
)

interface AppRouteChildren {
  AppAtividadesRoute: typeof AppAtividadesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDisciplinasRoute: typeof AppDisciplinasRoute
  AppTurmasRoute: typeof AppTurmasRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAtividadesRoute: AppAtividadesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDisciplinasRoute: AppDisciplinasRoute,
  AppTurmasRoute: AppTurmasRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
